#!/bin/sh

. ../common/start_functions.sh

router="R1"
dhcp_server="DHCP6server"
pcs="FIX PC1 PC2"

if [ $# -eq 1 ]; then
    eid=$1
    isEidRunning $eid
else
    eid=`isNodeRunning $dhcp_server`
    if [ $? -ne 0 ]; then
	exit 1
    fi
fi

if isOSfreebsd; then
    comm="rtadvd"
    hasPackage "$dhcp_server" "$eid" '^isc-dhcp.*-server'
    hasPackage "$dhcp_server" "$eid" '^isc-dhcp.*-client'
else
    comm="radvd"
fi

echo "Configuring router:"
hcp dhcp_$comm.conf ${router}@${eid}:/etc/$comm.conf
himage ${router}@${eid} killall $comm
himage -b ${router}@${eid} $comm eth1

echo "Configuring server:"
himage ${dhcp_server}@${eid} mkdir -p /var/db
himage ${dhcp_server}@${eid} touch /var/db/dhcpd6.leases
himage ${dhcp_server}@${eid} killall dhcpd

if isOSfreebsd; then
    hcp dhcpd6.conf ${dhcp_server}@${eid}:/usr/local/etc/dhcpd6.conf
    himage ${dhcp_server}@${eid} service isc-dhcpd6 onerestart
else
    hcp dhcpd6.conf ${dhcp_server}@${eid}:/etc/dhcp/dhcpd.conf
    himage ${dhcp_server}@${eid} touch /var/lib/dhcp/dhcpd6.leases
    himage -b ${dhcp_server}@${eid} dhcpd -6
fi

sleep 3
echo "Configuring clients:"
for pc in $pcs; do
	echo "++++++ $pc ++++++"
	himage ${pc}@${eid} killall dhclient
	if isOSfreebsd; then
	    pre="/usr/local/sbin/"
	    himage ${pc}@${eid} ifconfig eth0 inet6 -ifdisabled
	    himage ${pc}@${eid} ifconfig eth0 inet6 accept_rtadv
	    himage ${pc}@${eid} rtsol -D eth0
	fi
	himage ${pc}@${eid} ${pre}dhclient -6 -v -cf /dev/null eth0
done
