#! /bin/sh 

. ../common/start_functions.sh

dhcp_server="DHCPserver"
hosts="FIX PC1 PC2"

if [ $# -eq 1 ]; then
    eid=$1
    isEidRunning $eid
else
    eid=`isNodeRunning $dhcp_server`
fi

hasPackage "$dhcp_server" "$eid" '^isc-dhcp.*-server'

echo "Configuring server:"

# Stop dhcpd on DHCP server
himage ${dhcp_server}@${eid} killall -9 dhcpd 2> /dev/null
# and start it ...

hcp DHCPserver.dhcpd.conf ${dhcp_server}@${eid}:/tmp
himage ${dhcp_server}@${eid} touch /var/db/imunes-dhcpd.leases
himage ${dhcp_server}@${eid} dhcpd -d -cf /tmp/DHCPserver.dhcpd.conf >/dev/null 2>&1 &

echo
echo Configuring clients:
for i in $hosts
do
    isNodeRunning $i $eid
    himage ${i}@${eid} dhclient eth0
    himage ${i}@${eid} ifconfig eth0 | grep inet
done
