#! /bin/sh 

. ../common/start_functions.sh

dhcp_server="DHCPserver"
hosts="FIX PC1 PC2"

if [ $# -eq 1 ]; then
    eid=$1
    isEidRunning $eid
else
    eid=`isNodeRunning $dhcp_server`
    if [ $? -ne 0 ]; then
	exit 1
    fi
fi


if isOSfreebsd; then
    hasPackage "$dhcp_server" "$eid" '^isc-dhcp.*-server'
fi

echo "Configuring server:"

# Stop dhcpd on DHCP server
himage ${dhcp_server}@${eid} killall -9 dhcpd > /dev/null 2>&1
# and start it ...

hcp DHCPserver.dhcpd.conf ${dhcp_server}@${eid}:/tmp
himage ${dhcp_server}@${eid} mkdir -p /var/db/
himage ${dhcp_server}@${eid} touch /var/db/imunes-dhcpd.leases
if isOSlinux; then
    himage -b ${dhcp_server}@${eid} dhcpd -d -cf /tmp/DHCPserver.dhcpd.conf &
else
    himage ${dhcp_server}@${eid} dhcpd -d -cf /tmp/DHCPserver.dhcpd.conf >/dev/null 2>&1 &
fi

echo
echo Configuring clients:
for i in $hosts
do
    isNodeRunning $i $eid
    if isOSlinux; then
	himage ${i}@${eid} dhclient -v -1 eth0
    else
	himage ${i}@${eid} dhclient eth0
    fi
    himage ${i}@${eid} ifconfig eth0 | grep "inet "
done
